import { useState, useEffect, useRef } from 'react';
import api from '../api';
import { Wallet, TrendingUp, AlertTriangle, PiggyBank, ArrowUpRight, ArrowDownRight, Plus, Download, FileText } from 'lucide-react';
import clsx from 'clsx';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, Label } from 'recharts';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { useTheme } from '../context/ThemeContext.jsx';

const Dashboard = () => {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [month, setMonth] = useState(new Date().getMonth() + 1);
    const [year, setYear] = useState(new Date().getFullYear());
    const dashboardRef = useRef(null);
    const { isDark } = useTheme();

    useEffect(() => {
        const fetchData = async () => {
            try {
                const res = await api.get(`/analytics?month=${month}&year=${year}`);
                setData(res.data);
            } catch (error) {
                console.error('Error fetching dashboard data:', error);
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [month, year]);

    const handleExportPDF = async () => {
        const element = dashboardRef.current;
        if (!element) return;

        const canvas = await html2canvas(element, { scale: 2, backgroundColor: '#ffffff' });
        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

        pdf.setFillColor(255, 255, 255);
        pdf.rect(0, 0, pdfWidth, pdf.internal.pageSize.getHeight(), 'F');
        pdf.setFontSize(18);
        pdf.setTextColor(40);
        pdf.text('Student Expense Report', 15, 20);
        pdf.setFontSize(12);
        pdf.setTextColor(100);
        pdf.text(`Period: ${new Date(year, month - 1).toLocaleString('default', { month: 'long' })} ${year}`, 15, 30);
        pdf.addImage(imgData, 'PNG', 10, 40, pdfWidth - 20, pdfHeight - 20);
        pdf.setFontSize(10);
        pdf.setTextColor(150);
        pdf.text('Generated by ExpenseTracker', pdfWidth / 2, pdf.internal.pageSize.getHeight() - 10, { align: 'center' });
        pdf.save(`Expense_Report_${month}_${year}.pdf`);
    };

    if (loading) return <div className="p-8 text-center text-slate-500 animate-pulse">Loading dashboard...</div>;

    const COLORS = ['#0ea5e9', '#6366f1', '#10b981', '#f59e0b', '#ef4444'];
    const pieData = data?.categoryData ? Object.entries(data.categoryData).map(([name, value]) => ({ name, value })) : [];

    const StatCard = ({ title, value, icon: Icon, color, subtext, textClassName }) => (
        <div className="card group cursor-default relative overflow-hidden">
            <div className="absolute inset-x-0 top-0 h-2 bg-gradient-to-r from-primary to-secondary opacity-50" />
            <div className="relative z-10 p-4 pt-6">
                <div className="flex items-center justify-between mb-5">
                    <div className={clsx('p-3 rounded-2xl bg-opacity-20', color)}>
                        <Icon size={24} className={color.replace('bg-', 'text-')} />
                    </div>
                    {subtext && <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-[#111827] text-slate-300 border border-[#1f2937]">{subtext}</span>}
                </div>
                <p className="text-sm font-medium text-slate-400 uppercase tracking-wide">{title}</p>
                <h3 className={clsx('text-3xl font-bold mt-3 tracking-tight', textClassName || (isDark ? 'text-white' : 'text-slate-950'))}>₹{value?.toLocaleString() || 0}</h3>
            </div>
        </div>
    );

    return (
        <div className="space-y-8" ref={dashboardRef}>
            <div className={clsx('relative overflow-hidden rounded-[32px] p-8 shadow-[0_25px_70px_-40px_rgba(0,0,0,0.85)]', isDark ? 'bg-[#0B1120]/95 border border-[#111827]' : 'bg-white/95 border border-slate-200')}>
                <div className="absolute right-0 top-0 h-44 w-44 rounded-full bg-[#1DA1F2]/15 blur-3xl" />
                <div className="absolute left-0 bottom-0 h-56 w-56 rounded-full bg-[#6366f1]/10 blur-3xl" />
                <div className="relative z-10 grid gap-6 lg:grid-cols-[1.8fr_1.2fr] items-center">
                    <div>
                        <p className={clsx('text-sm font-semibold uppercase tracking-[0.35em]', isDark ? 'text-slate-400' : 'text-slate-500')}>Student Dashboard</p>
                        <h1 className={clsx('mt-3 text-4xl font-bold', isDark ? 'text-white' : 'text-slate-950')}>Track smarter. Save better.</h1>
                    </div>
                    <div className="grid gap-4 sm:grid-cols-2">
                        <div className={clsx('rounded-3xl p-5 shadow-[0_25px_45px_-35px_rgba(0,0,0,0.7)] border', isDark ? 'bg-[#111827] border-[#111827]/60' : 'bg-slate-50 border-slate-200')}>
                            <p className={clsx('text-sm uppercase tracking-[0.3em]', isDark ? 'text-slate-400' : 'text-slate-500')}>Savings</p>
                            <p className={clsx('mt-3 text-2xl font-semibold', isDark ? 'text-white' : 'text-slate-950')}>₹{data?.remaining?.toLocaleString()}</p>
                        </div>
                        <div className={clsx('rounded-3xl p-5 shadow-[0_25px_45px_-35px_rgba(0,0,0,0.7)] border', isDark ? 'bg-[#111827] border-[#111827]/60' : 'bg-slate-50 border-slate-200')}>
                            <p className={clsx('text-sm uppercase tracking-[0.3em]', isDark ? 'text-slate-400' : 'text-slate-500')}>Trend</p>
                            <p className={clsx('mt-3 text-2xl font-semibold', isDark ? 'text-white' : 'text-slate-950')}>{data?.totalSpent > data?.budget ? 'Over budget' : 'On track'}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
                <div>
                    <h2 className={clsx('text-3xl font-bold', isDark ? 'text-white' : 'text-slate-950')}>Overview</h2>
                    <p className={clsx('mt-1', isDark ? 'text-slate-400' : 'text-slate-600')}>Data for {new Date(year, month - 1).toLocaleString('default', { month: 'long' })} {year}</p>
                </div>
                <div className="flex flex-wrap items-center gap-3">
                    <div className={clsx('flex rounded-3xl p-1 shadow-[0_20px_45px_-30px_rgba(0,0,0,0.65)] border', isDark ? 'bg-[#0B1120] border-[#111827]' : 'bg-slate-100 border-slate-200')}>
                        <select
                            value={month}
                            onChange={(e) => setMonth(Number(e.target.value))}
                            className={clsx('bg-transparent text-sm font-medium px-3 py-2 rounded-2xl focus:outline-none cursor-pointer', isDark ? 'text-slate-300 hover:bg-[#111827]' : 'text-slate-700 hover:bg-slate-200')}
                        >
                            {Array.from({ length: 12 }, (_, i) => (
                                <option key={i + 1} value={i + 1}>{new Date(0, i).toLocaleString('default', { month: 'short' })}</option>
                            ))}
                        </select>
                        <div className={clsx('w-px my-1 mx-1', isDark ? 'bg-[#1f2937]' : 'bg-slate-300')} />
                        <select
                            value={year}
                            onChange={(e) => setYear(Number(e.target.value))}
                            className={clsx('bg-transparent text-sm font-medium px-3 py-2 rounded-2xl focus:outline-none cursor-pointer', isDark ? 'text-slate-300 hover:bg-[#111827]' : 'text-slate-700 hover:bg-slate-200')}
                        >
                            <option value={2024}>2024</option>
                            <option value={2025}>2025</option>
                            <option value={2026}>2026</option>
                        </select>
                    </div>
                    <button
                        onClick={handleExportPDF}
                        className={clsx('inline-flex items-center justify-center rounded-2xl border px-4 py-2 text-sm font-medium shadow-lg transition-all', isDark ? 'border-[#111827] bg-[#1DA1F2] text-white shadow-[#1DA1F2]/20 hover:bg-[#66bfff]' : 'border-slate-200 bg-sky-500 text-white shadow-sky-500/20 hover:bg-sky-400')}
                    >
                        <Download size={18} className="mr-2" /> Export PDF
                    </button>
                </div>
            </div>

            {data?.insight && (
                <div className={clsx('rounded-3xl border p-5 shadow-[0_20px_50px_-35px_rgba(0,0,0,0.7)] transition-all', isDark ? 'border-[#ef4444] bg-[#ef4444]/15 text-white' : 'border-[#fecaca] bg-[#fee2e2]/80 text-slate-950')}>
                    <div className="flex items-start gap-4">
                        <div className={clsx('rounded-2xl p-3 shadow-[0_12px_30px_-22px_rgba(239,68,68,0.5)]', isDark ? 'bg-black/10' : 'bg-slate-100')}>
                            {data?.alert ? <AlertTriangle size={20} className="text-[#ef4444]" /> : <TrendingUp size={20} className="text-[#ef4444]" />}
                        </div>
                        <div>
                            <p className={clsx('text-sm uppercase tracking-[0.25em]', isDark ? 'text-white/70' : 'text-slate-500')}>Insight</p>
                            <h3 className={clsx('mt-2 text-lg font-semibold', isDark ? 'text-white' : 'text-slate-950')}>{data?.alert ? 'Watch your spending' : 'Stay on top of your budget'}</h3>
                            <p className={clsx('mt-2 leading-7', isDark ? 'text-slate-200' : 'text-slate-700')}>{data.insight}</p>
                        </div>
                    </div>
                </div>
            )}

            <div className="grid grid-cols-1 gap-6 xl:grid-cols-4">
                <StatCard
                    title="Total Budget"
                    value={data?.budget}
                    icon={Wallet}
                    color="bg-sky-500 text-sky-500"
                    textClassName="text-black"
                />
                <StatCard
                    title="Total Spent"
                    value={data?.totalSpent}
                    icon={ArrowUpRight}
                    color="bg-orange-500 text-orange-500"
                    subtext={`${Math.round((data?.totalSpent / (data?.budget || 1)) * 100)}%`}
                    textClassName="text-black"
                />
                <StatCard
                    title="Remaining"
                    value={data?.remaining}
                    icon={PiggyBank}
                    color={data?.remaining < 0 ? 'bg-red-500 text-red-500' : 'bg-emerald-500 text-emerald-500'}
                />
                <StatCard
                    title="Wasted Money"
                    value={data?.totalWasted}
                    icon={ArrowDownRight}
                    color="bg-rose-500 text-rose-500"
                />
            </div>

            {data?.totalSpent === 0 ? (
                <div className="card py-16 flex flex-col items-center justify-center text-center">
                    <div className="bg-[#111827] p-6 rounded-full mb-6">
                        <FileText size={48} className="text-slate-400" />
                    </div>
                    <h3 className="text-xl font-bold text-white mb-2">No expenses yet</h3>
                    <p className="text-slate-500 max-w-sm mx-auto mb-8">
                        Start tracking your spending to see analytics and insights here.
                    </p>
                    <button className="btn btn-primary">Add your first entry</button>
                </div>
            ) : (
                <div className="grid grid-cols-1 gap-8 xl:grid-cols-[2fr_1fr]">
                    <div className="card overflow-hidden">
                        <div className="mb-6 flex items-center justify-between">
                            <div>
                                <h3 className={clsx('text-xl font-bold', isDark ? 'text-white' : 'text-slate-950')}>Daily Spending</h3>
                                <p className={clsx('text-sm', isDark ? 'text-slate-400' : 'text-slate-500')}>Last 30 days</p>
                            </div>
                            <span className={clsx('rounded-full px-3 py-1 text-xs uppercase tracking-[0.2em]', isDark ? 'bg-[#111827] text-slate-300' : 'bg-slate-200 text-slate-700')}>Trend</span>
                        </div>
                        <div className="flex h-64 items-end gap-2">
                            {data?.dailyData?.map((val, idx) => (
                                <div
                                    key={idx}
                                    style={{ height: `${Math.max(4, Math.min(100, (val / (Math.max(...data.dailyData) || 1)) * 100))}%` }}
                                    className="relative flex-1 rounded-full bg-sky-200/70 dark:bg-sky-500/30 hover:bg-sky-400 dark:hover:bg-sky-400 transition-all"
                                >
                                    <div className="absolute bottom-full left-1/2 hidden -translate-x-1/2 rounded-full bg-slate-900 px-2 py-1 text-[10px] text-white shadow-lg group-hover:block sm:block">
                                        ₹{val}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="card overflow-hidden">
                        <div className="mb-6 flex items-center justify-between">
                            <div>
                                <h3 className={clsx('text-xl font-bold', isDark ? 'text-white' : 'text-slate-950')}>Category Split</h3>
                                <p className={clsx('text-sm', isDark ? 'text-slate-400' : 'text-slate-500')}>Where your money goes</p>
                            </div>
                            <div className={clsx('rounded-full px-3 py-1 text-sm', isDark ? 'bg-[#111827] text-slate-300' : 'bg-slate-200 text-slate-700')}>Top 5</div>
                        </div>
                        <div className="h-64 min-h-[250px]">
                            {pieData.length > 0 ? (
                                <ResponsiveContainer width="100%" height="100%">
                                    <PieChart>
                                        <Pie
                                            data={pieData}
                                            cx="50%"
                                            cy="50%"
                                            innerRadius={70}
                                            outerRadius={90}
                                            paddingAngle={4}
                                            dataKey="value"
                                            stroke="none"
                                        >
                                            {pieData.map((entry, index) => (
                                                <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                            ))}
                                            <Label
                                                value={`₹${data.totalSpent?.toLocaleString()}`}
                                                position="center"
                                                className="fill-slate-900 dark:fill-white font-bold text-xl"
                                            />
                                        </Pie>
                                        <Tooltip
                                            formatter={(value) => `₹${value}`}
                                            contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', borderRadius: '8px', color: '#fff' }}
                                            itemStyle={{ color: '#fff' }}
                                        />
                                    </PieChart>
                                </ResponsiveContainer>
                            ) : (
                                <div className="flex h-full items-center justify-center text-slate-400">No data available</div>
                            )}
                        </div>
                        <div className="mt-6 space-y-3">
                            {pieData.slice(0, 4).map((entry, index) => (
                                <div key={index} className="flex justify-between items-center rounded-2xl bg-[#111827] px-4 py-3 transition-colors hover:bg-[#172031]">
                                    <div className="flex items-center gap-3">
                                        <div className="h-3 w-3 rounded-full shadow-sm" style={{ backgroundColor: COLORS[index % COLORS.length] }} />
                                        <span className="text-sm font-medium text-white">{entry.name}</span>
                                    </div>
                                    <span className="font-bold text-white">₹{entry.value.toLocaleString()}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Dashboard;
